version: '3.3'
services:
  mysqldb:
    image: mysql:8
    container_name: ski_db

    environment:
      MYSQL_DATABASE: 'mysqldb'

      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'


    volumes:
      - /home/mysql/data:/var/lib/mysql
  app:

    image: aminebarguellil/skiapp

    container_name: ski_app

    restart: on-failure

    ports:

      - '9092:9092'

    depends_on:

      - 'mysqldb'